 platform :ios, '10.0'

target 'SportsProject' do

  use_frameworks!

  # Pods for SportsProject
  pod 'Alamofire', '~> 5.2'
  pod "YoutubePlayer-in-WKWebView", "~> 0.2.0"
  pod 'SDWebImage'
  pod 'SwiftyJSON'

end
